name: le johann
favicon: null
layout_spectrum: 0.91986
typography_spectrum: 0.07325
title: The colossal colossus´s colca canyon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050306'
    - '#f4f3f8'
    - '#333235'
    - '#666053'
    - '#b7a599'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0
purpose:
  - name: null
    item: null
    url: null
