typography_spectrum: 0.26697
color:
  brandColors:
    - '#caeaf5'
    - '#26372d'
    - '#858a84'
    - '#8ec05d'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: le johann
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Milky is the Way
purpose: []
