name: le johann
favicon: null
layout_spectrum: 0
typography_spectrum: 0.26697
title: The colossal colossus´s colca canyon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#caeaf5'
    - '#26372d'
    - '#858a84'
    - '#8ec05d'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
